- .gitignore
- .travis.yml
- README.md
- package.json
Closes #14
Thanks @Hongarc for mentioning this!
> Report coverage to Codecov

- index.js
- matcher.js
- test/matcher.test.js
- test/switch.test.js
> Make it possible to use arbitrary non-Route elements inside of a Switch

- matcher.js
- drop keys arg pathToRegexp function
- simplify getRegexp function
> refactoring matcher

- use-location.js
> add useEffect deps

- README.md
- index.js
- package.json
- test/switch.test.js
> Fix Switch/Route rendering consistency

- .gitignore
- index.d.ts
- matcher.d.ts
- package.json
- preact/index.d.ts
- static-location.d.ts
- use-location.d.ts
> Move typings from DefinitelyTyped

- index.d.ts
- package.json
- preact/index.d.ts
According to #51 and #52.
Also, I think we need to add typings files to `files` field in package.json, right?
> Add `replace` param to PushCallback type

- .gitignore
- package.json
- preact/package.json
- preact/types/index.d.ts
- preact/types/tsconfig.json
- preact/types/type-specs.tsx
- types/index.d.ts
> Preact typings, `npm pack` files and minor typings changes

- README.md
- package.json
- test/use-location.test.js
- use-location.js
Closes #69 Also has a regression spec to verify this behaviour.
> Properly cache `setLocation` argument

- package.json
- preact/react-deps.js
It's been merged into core, in part because we want Wouter to have first-class support!
/cc @kristoferbaxter
> Use isValidElement from preact core

- index.js
for smaller! We can reduce a few bytes again. 😄
> We can reduce a few bytes again.

- index.js
Reduces index.js size by 3 bytes
> Reduce `useRoute` size

- README.md
- index.js
- package.json
- test/link.test.js
- test/use-location.test.js
- types/index.d.ts
- types/preact/index.d.ts
- types/preact/type-specs.tsx
- types/type-specs.tsx
- use-location.js
Closes #76 
Reduce the bundle size by 5 bytes.
@cbbfcd could you check out the types?
> Rename `basepath` to `base`

- index.js
- test/switch.test.js
[#101 ](https://github.com/molefrog/wouter/issues/101), we hava a size trouble, +5b～
> Add another default route matching rule

- types/index.d.ts
- types/preact/index.d.ts
- types/preact/type-specs.tsx
- types/type-specs.tsx
since we can difine the default route through non-path.
there should some update to the type-definition file.
> update ts definition

- index.js
as [#114](https://github.com/molefrog/wouter/issues/114).
> feat: support replace props in <Redirect /> components

- types/index.d.ts
add `replace?: boolean` for Redirect component
> feat: update the ts file

- index.js
>  Small optimization, less code size

- .gitignore
- types/index.d.ts
- types/type-specs.tsx
This PR continue the work done in https://github.com/molefrog/wouter/pull/121
> Types with support for custom hooks and navigation options

- package.json
- types/index.d.ts
- types/matcher.d.ts
- types/preact/index.d.ts
- types/preact/tsconfig.json
- types/preact/type-specs.tsx
- types/use-location.d.ts
Move related types to `./use-location` and `./matcher` files.
> Refactor types

- README.md
> Add strict routes section to FAQ

- test/preact.test.js
- test/switch.test.js
- test/use-router.test.js
> feat: remove unused code

- index.js
- test/redirect.test.js
- test/test-utils.js
for [#136](https://github.com/molefrog/wouter/issues/136)
> fix: useLayoutEffect should return nothing

- index.js
- matcher.js
- package.json
- preact/react-deps.js
- react-deps.js
- test/custom-matcher.test.js
- test/matcher.test.js
- test/preact.test.js
- test/redirect.test.js
- test/route-rendering.test.js
- test/ssr.test.js
- test/static-location.test.js
- test/switch.test.js
- test/test-utils.js
- test/use-router.test.js
- use-location.js
This PR:
- adds [husky](https://github.com/typicode/husky) to manage git hooks
- does **NOT** add prettier configuration, because Prettier doesn't support global configuration, whereas @molefrog mentioned he [would like to stick to a default](https://github.com/molefrog/wouter/pull/141#issuecomment-714594175) prettier config
- contains autofixes
> feat: Autofixing formatting issues

- package.json
- Proper peer dependency version
- Update all React-related packages to be able to test the library with the new version of React
> Proper React 17 setup

- test/use-location.test.js
- use-location.js
support search url like `/foo?hello=world`
> feat: support search url

- package.json
- test/use-location.test.js
- use-location.js
> Fix: useLocation() path should not contain the search query

- package.json
To make sure the size limit check passes.
> Adjust size limits

- use-location.js
reduce the code size a little bit. 🚀
> feat: reduce a little code size

- use-location.js
> feat: Continue to reduce code size

- index.js
- test/switch.test.js
This allows conditional routes inside `<Switch>`, for example:
```jsx
<Switch>
{user && <Route … />}
<Route … />
</Switch>
```
> Update flattenChildren to handle null values

- .gitignore
- package.json
- test/test-utils.js
- types/index.d.ts
- types/matcher.d.ts
- types/type-specs.tsx
Closes #210 
This will probably be a breaking change for TS users who manually typed their path params, I'm not sure if that warrants a major 🤔 Open to alternative approaches as well.
> TypeScript: Infer params from path

- index.js
- test/link.test.js
> Prevent navigation when event was cancelled

- types/router.d.ts
- types/ts3.9.4/index.d.ts
- types/ts3.9.4/tsconfig.json
- types/ts3.9.4/type-specs.tsx
- types/ts4.1/index.d.ts
- types/ts4.1/tsconfig.json
- types/ts4.1/type-specs.tsx
> Fix missing parent Router declarations

- README.md
- index.js
- package.json
- preact/package.json
- preact/react-deps.js
- preact/types/use-location.d.ts
- react-deps.js
- static-location.js
- test/preact.test.js
- test/use-location.test.js
- types/router.d.ts
- types/use-location.d.ts
- use-location.js
Fixes #232 and fixes #58. 
Also fixes #140.
Also, simplifies existing code with `useEvent` and fixes a couple bugs along the way.
> add useSyncExternalStore

- .github/workflows/ci-tests.yml
- .github/workflows/size.yml
- package.json
- rollup.config.mjs
The build command in package.js has become quite messy.
> Create external Rollup config

- package.json
> Move @rollup/plugin-replace to devDependencies

- package.json
> Explicit TS4.1 types support in package.json

- package.json
- packages/wouter-preact/package.json
- packages/wouter/package.json
- watch command for monorepo
----
run `npm run watch` and `npm run test` for developing
> feat(v3): watch command

- package.json
- packages/wouter/src/use-browser-location.js
- packages/wouter/test/history-patch.test.ts
Patch history once
related to #346
closes #167
> v3: Patch history once

- packages/wouter/src/index.js
- packages/wouter/test/nested-route.test.tsx
- packages/wouter/test/test-utils.tsx
See nested routing specification in #343
> Native route nesting

- packages/wouter/src/paths.js
- packages/wouter/src/use-browser-location.js
- packages/wouter/test/global-this-at-component-level.test.tsx
- packages/wouter/test/global-this-at-top-level.test.ts
- packages/wouter/tsconfig.json
- packages/wouter/types/use-browser-location.d.ts
- test all hooks in node
this should fix #345 and #344
> v3: make all hooks from `use-browser-location` compatible with node

- packages/wouter/test/link.test-d.tsx
- packages/wouter/test/link.test.tsx
- packages/wouter/types/index.d.ts
> v3: added ref type to the `Link` component

- packages/wouter-preact/types/index.d.ts
- packages/wouter/src/index.js
- packages/wouter/test/use-params.test-d.ts
- packages/wouter/test/use-params.test.tsx
- packages/wouter/types/index.d.ts
Reimplementation of `useParams` hook from v2 with better generics.
> V3: `useParams` hook

- packages/wouter/test/use-location.test.tsx
from comment: 
https://github.com/molefrog/wouter/pull/362/files#r1360523586
> v3: refactor to describe each

- packages/wouter/src/memory-location.js
- packages/wouter/test/memory-location.test-d.ts
- packages/wouter/test/memory-location.test.ts
- packages/wouter/test/use-location.test.tsx
- packages/wouter/types/memory-location.d.ts
> v3: Add `reset` method to memory location constructor

- packages/wouter-preact/types/use-browser-location.d.ts
- packages/wouter/src/paths.js
- packages/wouter/src/use-browser-location.js
- packages/wouter/src/use-hash-location.js
- packages/wouter/test/global-this-at-component-level.test.tsx
- packages/wouter/test/use-browser-location.test-d.ts
- packages/wouter/test/use-browser-location.test.tsx
- packages/wouter/test/use-hash-location.test.tsx
- packages/wouter/types/use-browser-location.d.ts
> Location string preprocessing

- packages/wouter/package.json
- packages/wouter/src/index.js
- packages/wouter/test/nested-route.test.tsx
- packages/wouter/test/use-params.test.tsx
I found this bug while testing v3 on a real app.
> Nested optional root segments

- packages/wouter/src/index.js
- packages/wouter/src/use-browser-location.js
- packages/wouter/src/use-hash-location.js
- packages/wouter/test/global-this-at-component-level.test.tsx
- packages/wouter/test/use-browser-location.test.tsx
- packages/wouter/test/use-hash-location.test.tsx
- packages/wouter/test/use-location.test.tsx
- packages/wouter/test/use-search.test.tsx
> v3: Move unescape to core
